security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Utilisateur:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: /principal
            logout:
                path: logout
                target: /principal

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/register, roles: ROLE_ADMIN }
         - { path: ^/principal/listeUtilisateur, roles: ROLE_ADMIN }
         - { path: ^/register/registerPatient, roles: ROLE_PATIENT }
         - { path: ^/register/registerMedecin, roles: ROLE_MEDECIN }
         - { path: ^/register/registerAssistant, roles: ROLE_ASSISTANT }

    role_hierarchy:
        ROLE_ADMIN: ROLE_MEDECIN,ROLE_ASSISTANT, ROLE_PATIENT
